### PR TITLE
Added compatibility for Proxy objects

### PR DESCRIPTION
**Pull request by ultimate-tester**
Added a check to see which method to use based on browser compatibility
Made html preview pages more HTML5 compliant (html tag, lang attribute)
Split up updating bindings and updating single bindings
Added a force flag to bindings to force updating without checking for changes (to speed up update)
Adjusted the README to reflect necesary changes
Assured backwards compatibility

### CODE REVIEW

**Comment by chandlerprall** [comment]
What do you think about using `Object.defineProperty`/`Object.defineProperties` instead? That has better browser support and generally faster as proxies haven't been optimized by JS engines yet.

**Comment by ultimate-tester** [comment]
Why not both? I think Proxy will eventually be the best, but would like to see support from the somewhat older browsers as well, fully agree. I am not sure if the setter of a property will also trigger if the content of an array is changed (like a Proxy will). This is required for your example with the list as well, otherwise that'd be broken. I'll experiment a little.

The only con I see with defineProperty is that we have to manually proxy the object (which is fine) but we are actually modifying the object itself where a proxy is completely hidden. I'm not sure if this would have any effect to how the user can still use the object afterwards. What if it already is a property, will it overwrite? I basically have some questions.. most of them should be simple enough though, I don't think many users will have advanced logic inside their context object for nunjucks. There's no reason to have this.. but who knows.

I'll play around with it a little to see if it's feasible.

**Comment by ultimate-tester** [comment]
I've played around a little. It's not as straightforward unfortunately. I'll merge this pull request first, but create another issue to support defineProperty.

**Comment by chandlerprall** [comment]
No need to add support for `defineProperty`, your explanation of why `Proxy` works better makes a lot of sense. Up to you though :)

**Pull request merged**
